### PR TITLE
Reverting deployer to run on loop

### PR DESCRIPTION
**Pull request by Zapadlo**
In light of recent problem regarding network interface, timing out
naming resolution, its probably a safer bet to run deployer on loop and
restart when it fails.

### CODE REVIEW

**Comment by martingartonft** [comment]
lgtm. (assuming corresponding service files stuff is coming soon..)

**Comment by Zapadlo** [comment]
Ofc ^^

**Comment by Nesze** [comment]
+1

**Comment by catalin-ilea** [comment]
+1

**Comment by kovacshuni** [comment]
+1

**Pull request merged**
