### PR TITLE
Debug switch

### PR DESCRIPTION
**Pull request by tamas-molnar**
* added debug switch to enable/disable debug logs - this will make it easier to debug deployer issues as we can leave the debug logs in and enable them when necessary
* minor linter and formatting fixes
* don't know why the circleci build is failing, it builds fine on dockerhub

### CODE REVIEW

**Comment by kovacshuni** [comment]
+1

**Comment by tosan88** [comment]
:+1:

**Comment by khatton-ft** [comment]
The Fleet API required Go 1.6, the simplest way to fix CircleCI is probably to upgrade the environment to Ubuntu 14, which has the right version. Then :+1:

**Comment by tamas-molnar** [comment]
@khatton-ft That did the trick, thanks!

**Pull request merged**
