### PR TITLE
Stop needlessly logging, don't reset state needlessly

### PR DESCRIPTION
**Pull request by Zapadlo**

### CODE REVIEW

**Comment by martingartonft** [comment]
You move fast.  Preprod first for a day?

**Comment by Zapadlo** [comment]
Thats actually tricky... Yes, we could do that

**Comment by Zapadlo** [comment]
Ok, pushed `coco/coco-fleet-deployer:chillout-deployer` to pre-prod, will merge next week if its fine.

**Comment by catalin-ilea** [comment]
lgtm

**Pull request merged**
